MODE: 'test' # train/test
OUTPUT_PATH: '../output/test'
EPOCHS: 2000
START_EPOCH: 0
LOG_INTERVAL: 100
CUDA_DEVICE: 0 #'cuda0'
BATCH_SIZE: 32
NUM_WORKERS: 4
SNAPSHOT_INTERVAL: 5
SAVE_FEATURES: True
TOPK: [1]
STEP: [0.5, 0.75, 0.875]
EVAL_INTERVAL: 1
TERMINAL_LOG: True
WARM_START: False

# Model parameters
MODEL:
  TYPE: 'stgcn'
  OPTIMIZER: 
    TYPE: 'sgd'
    LR: 0.001
    WEIGHT_DECAY: 0.1
  LOSS: 'cross_entropy'
  TARGETS: ['emotion_classes']
  SNAPSHOT_PATH: ''

# Data params
DATA:
  TYPE: 'multi_view'
  COORDS: 3 # in channels
  JOINTS: 16
  CYCLES: 1
  FEATURES_FILE: '/scratch/emotiongroup/data/test/features_*.h5'
  LABELS_FILE: '/scratch/emotiongroup/data/test/labels_*.h5'
  
# Test / Inference
TEST:
  MODEL_FOLDER: '/home/emotiongroup/emotionGroup/emotion-bot/output/saved_models/stgcn/23-02-2020-00-55-10'
  MODEL_NAME: 'epoch2_acc35.12_model.pth.tar'
