MODE: 'test' # train/test
OUTPUT_PATH: '../output_test'
EPOCHS: 2000
START_EPOCH: 155
LOG_INTERVAL: 100
CUDA_DEVICE: 0 #'cuda0'
BATCH_SIZE: 32
NUM_WORKERS: 4
SNAPSHOT_INTERVAL: 5
SAVE_FEATURES: True
TOPK: [1]
STEP: [0.25, 0.5, 0.75]
EVAL_INTERVAL: 1
TERMINAL_LOG: True
WARM_START: False

# Model parameters
MODEL:
  TYPE: 'vs_gcnn'
  DROPOUT: 0.2
  OPTIMIZER: 
    TYPE: 'adam'
    LR: 0.01
    WEIGHT_DECAY: 0.00001
  LOSS: 'cross_entropy'
  TARGETS: ['emotion_classes', 'groups']
  LAYER_CHANNELS: [32, 64, 16]

# Data params
DATA:
  TYPE: 'multi_view'
  COORDS: 3 # in channels
  JOINTS: 16
  CYCLES: 1
  FEATURES_FILE: '/scratch/emotiongroup/data/test/features_*.h5'
  LABELS_FILE: '/scratch/emotiongroup/data/test/labels_*.h5'

# Test / Inference
TEST:
  MODEL_FOLDER: '/scratch/emotiongroup/Run 3/saved models/vs_gcnn/23-02-2020-00-32-48'
  MODEL_NAME: 'epoch123_acc50.81_model.pth.tar'
