MODE: 'train' # train/test
DATA_PATH: '/data/*.h5'
OUTPUT_PATH:
EPOCHS: 500
LOG_INTERVAL: 1
CUDA_DEVICE: '' 
BATCH_SIZE: 32
SNAPSHOT_INTERVAL: 5

# Model parameters

MODEL:
  TYPE: 'vscnn'
  OPTIMIZER: 
    TYPE: 'SGD'
    LR: 0.1
  LOSS: 'cross_entropy'
  SNAPSHOT_PATH: ''