MODE: 'train' # train/test/save_fearures
OUTPUT_PATH: '../output/vscnn_vgp'
EPOCHS: 2000
START_EPOCH: 0
LOG_INTERVAL: 1
CUDA_DEVICE: 0 #'cuda0'
BATCH_SIZE: 32
NUM_WORKERS: 4
SNAPSHOT_INTERVAL: 5
SAVE_FEATURES: True
TPOK: [1]
SAVE_FILE: '../output/vscnn_vgf/deepfeatures.h5'
STEP: [0.5, 0.75, 0.875]
PAVI_LOG: True
EVAL_INTERVAL: 10
WORK_DIR: '../logs/vscnn_vgf'
TERMINAL_LOG: True

# Model parameters
MODEL:
  TYPE: 'vscnn_view_group_feature'
  DROPOUT: 0.5
  OPTIMIZER: 
    TYPE: 'sgd'
    LR: 0.1
    WEIGHT_DECAY: 0.1
  LOSS: 'cross_entropy'
  SNAPSHOT_PATH: '../output/vscnn_vgp'
  SKCNN_LAYER_CHANNELS: [32, 64]

# Data params
DATA:
  TYPE: 'multi_view'
  COORDS: 3 # in channels
  JOINTS: 16
  CYCLES: 1
  FEATURES_FILE: '../data/test/features_*.h5'
  LABELS_FILE: '../data/test/labels_*.h5'