MODE: 'train' # train/test/save_fearures
OUTPUT_PATH: '../output/vscnn'
EPOCHS: 500
START_EPOCH: 0
LOG_INTERVAL: 1
CUDA_DEVICE: 0 #'cuda0'
BATCH_SIZE: 32
NUM_WORKERS: 4
SNAPSHOT_INTERVAL: 5
SAVE_FEATURES: True
TPOK: [1]
SAVE_FILE: '../output/vscnn/deepfeatures.h5'
STEP: [0.5, 0.75, 0.875]
LOG_INTERVAL: 1 # 100
PAVI_LOG: True
EVAL_INTERVAL: 10
WORK_DIR: '../logs/vscnn'
TERMINAL_LOG: True

# Model parameters
MODEL:
  TYPE: 'vscnn'
  OPTIMIZER: 
    TYPE: 'sgd'
    LR: 0.1
    WEIGHT_DECAY: 0.1
  LOSS: 'cross_entropy'
  SNAPSHOT_PATH: '../output/vscnn'

# Data params
DATA:
  TYPE: ''  # Data name
  COORDS: 3
  JOINTS: 16
  CYCLES: 1
  FEATURES_FILE: '../data/features.h5'
  LABELS_FILE: '../data/labels.h5'